[package]
name = "bs_box2d"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wrapped2d = "0.4.1"
parking_lot = "0.11.1"